name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: mvn install

      # Step 5: Build the project
      - name: Build the project
        run: mvn compile

      # Step 6: Run tests
      - name: Run tests
        run: mvn test

      # Step 7: Upload test results (optional)
     # - name: Upload test results
      #  uses: actions/upload-artifact@v3
      #  with:
       #   name: test-results
        #  path: target/surefire-reports/
