name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn clean package  

    - name: Build Docker Image
      run: docker build -t <dockerhub username> / <image name> . 

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push <dockerhub username> / <Image Name>:latest  
