name: Docker compose pipeline

on:
  schedule:
  - cron: "0 8 * * *"
jobs:
 test-schedule:
  name: start ec2
  runs-on: ubuntu-latest

  steps: 
   - name: ssh connection
   - uses: appleboy/ssh-action@v0.1.3
     with: 
      host: ${{secrets.AWS_EC2_HOST}}
      username: ${{secrets.AWS_EC2_USER}}
      scripts: |
       
       cd ${{secrets.DOCKER_COMPOSE_PATH}}
       docker-compose up -d
 
