name: Start EC2 Instance

on:
 schedule:
 - cron: '30 3 * * 1-5'  

jobs:
  start-ec2:
    runs-on: ubuntu-latest

    steps:

      - name: Start AWS EC2
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: start Ec2
        run: |
          
          echo ${{ secrets.INSTANCE_ID }}
          aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_ID }}

      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      
      - name: AWS EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd ${{ secrets.DOCKER_COMPOSE_PATH }}
            sudo docker-compose up -d  
          EOF
       
          
