name: Stop EC2 Instance

on:
  schedule:
    - cron: '30 16 * * 1-5'   

jobs:
  stop-ec2:
    runs-on: ubuntu-latest

    steps:

      - name: Stop AWS EC2
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: stop Ec2
        run: |
          aws ec2 stop-instances --instance-ids ${{secrets.INSTANCE_ID }}
       

          
